### ISSUE TITLE
Class 'nullx27\ESI\Configuration' not found

### ISSUE THREAD

**Issue by userbig** [nullx27/easi#5]
Try to you basic code and get this error:
`$easi = new \nullx27\Easi\Easi();
 $alliance = $easi->alliance->getAllianceById(99006112);
 print $alliance->allianceName;`

> Class 'nullx27\ESI\Configuration' not found

Using laravel 5.5

**Comment by Revenantal** [comment]
Was there a solution to this? I'm assuming you solved it after you closed it?

**Comment by userbig** [comment]
I`m cant remember whan happend with that solution, but i have new issue (?)

```
>>> $easi = new \nullx27\Easi\Easi()
=> nullx27\Easi\Easi {#2378}
>>> $alliance = $easi->alliance->getAlliance(99006112);
PHP Error:  Call to undefined method nullx27/ESI/Configuration::getDefaultHeaders() in D:/php/eve/vendor/nullx27/esi-php/src/ApiClient.php on line 144

```

**Comment by nullx27** [comment]
Hi, easi is dead. Please use https://github.com/nullx27/conduit
